/* 
// LANGUAGE text, header file  (utilized for localizations)
//
*/

// SCG[11/9/99]: no need for this anymore, we're doing things the smart way.
//#define TONGUE_ENGLISH
//#define TONGUE_FRENCH
//#define TONGUE_GERMAN
//#define TONGUE_ITALIAN
//#define TONGUE_SPANISH
//#define TONGUE_JAPANESE



//constants used to access graphics in the different fonts.

// toenail = buttons used on <------> graphics
#define TOENAIL_LEFT_DISABLE_STRING   "\x014"
#define TOENAIL_LEFT_OFF_STRING       "\x015"
#define TOENAIL_LEFT_ON_STRING        "\x016"
#define TOENAIL_RIGHT_DISABLE_STRING  "\x017"
#define TOENAIL_RIGHT_OFF_STRING      "\x018"
#define TOENAIL_RIGHT_ON_STRING       "\x019"


#define TOENAIL_UP_DISABLE_STRING     "\x0e"
#define TOENAIL_UP_OFF_STRING         "\x00f"
#define TOENAIL_UP_ON_STRING          "\x010"
#define TOENAIL_DOWN_DISABLE_STRING   "\x011"
#define TOENAIL_DOWN_OFF_STRING       "\x012"
#define TOENAIL_DOWN_ON_STRING        "\x013"

//#define TRIARROW_LEFT_STRING          "\x0a4"
//#define TRIARROW_RIGHT_STRING         "\x0d1"
//#define TRIARROW_UP_STRING            "\x081"
//#define TRIARROW_DOWN_STRING          "\x0a6"

#define ARROW_LEFT_STRING             "\x080"
#define ARROW_UP_STRING               "\x081"
#define ARROW_DOWN_STRING             "\x08d"
#define ARROW_RIGHT_STRING            "\x08e"

#define SYMBOL_RADIOBUTTON            "\x08f"
#define INSERTION_BAR_CHAR           ('\x05f')		 // 95


enum tongue_artifacts_enum
{
	T_PICKUP_WEAPON = 0,
	T_PICKUP_HEALTH,
	T_PICKUP_ARMOR_GOOD,
	T_PICKUP_BOOST,
	T_PICKUP_SAVEGEM,

	T_USEBOOST_POWER,
	T_USEBOOST_ATTACK,
	T_USEBOOST_SPEED,
	T_USEBOOST_ACRO,
	T_USEBOOST_VITA,

	T_BOMB_EXPLODE,
	T_BOMB_NEED_BOTTLE,
	T_BOMB_ITEM_REQUIRED1,
	T_BOMB_CREATED,
	T_BOMB_FOUND,
	T_BOMB_INGREDIENT_1,
	T_BOMB_INGREDIENT_2,
	T_BOMB_INGREDIENT_3,
	T_BOMB_BOTTLE,

	T_BOMB_INGREDIENT_SHORT_1,
	T_BOMB_INGREDIENT_SHORT_2,
	T_BOMB_INGREDIENT_SHORT_3,

	T_BOOK_READ,
	T_BOOK_NO_READ,
	T_BOOK_WYNDRAX,
// SCG[12/5/99]: 	T_BOOK_EVIL,

	T_KEY_PICKUP,
	T_KEY_CRYPT,
	T_KEY_WYNDRAX,
	T_KEY_PRISONCELL,

	T_KEY_RED_CARD,
	T_KEY_BLUE_CARD,
	T_KEY_GREEN_CARD,
	T_KEY_YELLOW_CARD,
	T_KEY_HEX_KEYSTONE,
	T_KEY_QUAD_KEYSTONE,
	T_KEY_TRIGON_KEYSTONE,
	T_MEGASHIELD,
	T_SKULL_OF_INVINCIBILITY,
	T_POISON_ANTIDOTE,
	T_DRACHMA,
	T_HORN,
	T_KEY_AEGIS_A,
	T_KEY_AEGIS_E,
	T_KEY_AEGIS_G,
	T_KEY_AEGIS_I,
	T_KEY_AEGIS_S,
	T_PURIFIER_SHARD,
	T_BLACK_CHEST,
	T_RING_OF_FIRE,
	T_RING_OF_UNDEAD,
	T_RING_OF_LIGHTNING,
	T_ENVIROSUIT,

	T_HEALTH_KIT, 
	T_GOLDENSOUL,
	T_WRAITHORB,
  
	T_SAVEGEM,
	T_NO_SAVEGEMS,							// cek[12-13-99]

	T_HEALTH_VIAL,							// cek[1-3-00]

	// cek[2-2-00]: altered the following ***********************************************
	T_HEALTH_E1_PACK,
	T_HEALTH_E2_VASE,
	T_HEALTH_E3_FLASK,
	T_HEALTH_E3_CRATE,
	T_HEALTH_E4_BOX,
	T_ANTIDOTE_EMPTY,

	T_AEGIS_FOUND,
	T_KEYSTONES_FOUND,
	T_PURIFIER_FOUND
};


enum tongue_menu_enum
{
	// menu-related
	T_MENU_KCC_FORWARD,
	T_MENU_KCC_BACKWARD,
	T_MENU_KCC_STEP_LEFT,
	T_MENU_KCC_STEP_RIGHT,
	T_MENU_KCC_ATTACK,
	T_MENU_KCC_UP_JUMP,
	T_MENU_KCC_OPERATE,
	T_MENU_KCC_DOWN_CROUCH,
	T_MENU_KCC_WEAPON_NEXT,
	T_MENU_KCC_WEAPON_PREV,
	T_MENU_KCC_TURN_LEFT,
	T_MENU_KCC_TURN_RIGHT,
	T_MENU_KCC_RUN,
	T_MENU_KCC_SIDESTEP,
	T_MENU_KCC_LOOK_UP,
	T_MENU_KCC_LOOK_DOWN,
	T_MENU_KCC_CENTER_VIEW,
	T_MENU_KCC_MOUSE_LOOK,
	T_MENU_KCC_KEYBOARD_LOOK,
	T_MENU_KCC_SCREEN_UP,
	T_MENU_KCC_SCREEN_DN,
	T_MENU_KCC_SHOW_HUDS,
	T_MENU_KCC_INV_OPEN,
	T_MENU_KCC_INV_USE,
	//  T_MENU_KCC_INV_DROP,
	T_MENU_KCC_INV_NEXT,
	T_MENU_KCC_INV_PREV,
	T_MENU_KCC_SWAP_SIDEKICK,
	T_MENU_KCC_COMMANDS_NEXT,
	T_MENU_KCC_COMMANDS_PREV,
	T_MENU_KCC_COMMANDS_ACT,

	T_MENU_ARROWS_LEFT,
	T_MENU_ARROWS_UP,
	T_MENU_ARROWS_DOWN,
	T_MENU_ARROWS_RIGHT,
	T_MENU_NOKEYSETTING,

	T_MENU_SETDELETE,
	T_MENU_SELECT,
	T_MENU_SETABORT,
	T_MENU_DEFAULTS,

	T_MENU_NONE_STRING,
	T_MENU_MOUSE_MOVE_LEFTRIGHT,
	T_MENU_MOUSE_TURN_LEFTRIGHT,
	T_MENU_MOUSE_LOOK_UPDOWN,
	T_MENU_MOUSE_MOVE_FORWARDBACK,
	T_MENU_MOUSE_REVERSEAXIS,
	T_MENU_MOUSE_MOUSELOOK,
	T_MENU_MOUSE_LOOKSTRAFE,

	T_MENU_MOUSE_XAXIS,
	T_MENU_MOUSE_YAXIS,
	T_MENU_MOUSE_BUTTON1,
	T_MENU_MOUSE_BUTTON2,
	T_MENU_MOUSE_BUTTON3,

	T_MENU_MOUSE_SELECT_ACTION,

	T_MENU_MOUSE_TURN_LR,
	T_MENU_MOUSE_STRAFE_LR,
	T_MENU_MOUSE_LOOK_UD,
	T_MENU_MOUSE_MOVE_FB,

	T_MENU_MOUSE_SENSITIVITY_X,
	T_MENU_MOUSE_SENSITIVITY_Y,
	T_MENU_MOUSE_HEADER,

	T_MENU_DEATHMATCH,
	T_MENU_DEATHTAG,
	T_MENU_COOPERATIVE,

	T_MENU_EASY,
	T_MENU_MEDIUM,
	T_MENU_HARD,

	T_MENU_FIND_INTERNET,			// SCG[12/1/99]: 
	T_MENU_FIND_LOCAL,				// SCG[12/1/99]: 
	T_MENU_START_MULTIPLAYER,		// SCG[12/1/99]: 

	T_MENU_LAN_CONNECT,
	T_MENU_INTERNET_CONNECT,

	T_MENU_JOIN_SERVER,
	T_MENU_START_SERVER,
	T_MENU_MP_ADD,
	T_MENU_MP_REFRESH,
	T_MENU_SETUP_PLAYER,

	//T_MENU_HANDEDNESS,
	//T_MENU_HANDEDNESS_LEFT,
	//T_MENU_HANDEDNESS_CENTER,
	//T_MENU_HANDEDNESS_RIGHT,

	T_MENU_CONNECTSPEED,
	T_MENU_CONNECTSPEED_1,
	T_MENU_CONNECTSPEED_2,
	T_MENU_CONNECTSPEED_3,
	T_MENU_CONNECTSPEED_4,
	T_MENU_CONNECTSPEED_5,
	T_MENU_CONNECTSPEED_6,

	T_MENU_COOP_TIME_LIMIT,
	T_MENU_COOP_COLOR,
	T_MENU_COOP_EPISODE,
	T_MENU_TEAM_CHOICE,
	T_MENU_CTF_LIMIT,
	T_MENU_TEAM1_COLOR,
	T_MENU_TEAM2_COLOR,
	T_MENU_SCORE_LIMIT,
	T_MENU_FRAG_LIMIT,
	T_MENU_LEVEL_LIMIT,
	T_MENU_GAME_EPISODE,
	T_MENU_GAME_MAP,
	T_MENU_GAME_MODE,
	T_MENU_SKILL_LEVEL,
	T_MENU_TIME_LIMIT,
	T_MENU_MAX_PLAYERS,
	T_MENU_MODELNAME,
	T_MENU_SKINCOLOR,
	T_MENU_MULTIPLAYER_GO,

	T_MENU_MPO_WEAPONS_STAY,
	T_MENU_MPO_ITEMS_RESPAWN,
	T_MENU_MPO_SPAWN_FARTHEST,
	T_MENU_MPO_ALLOW_EXITING,
	T_MENU_MPO_SAME_MAP,
	T_MENU_MPO_FORCE_RESPAWN,
	T_MENU_MPO_FALLING_DAMAGE,
	T_MENU_MPO_INSTANT_POWERUPS,
	T_MENU_MPO_ALLOW_POWERUPS,
	T_MENU_MPO_ALLOW_HEALTH,
	T_MENU_MPO_ALLOW_ARMOR,
	T_MENU_MPO_INFINITE_AMMO,
	T_MENU_MPO_FIXED_FOV,
	T_MENU_MPO_TEAMPLAY,
	T_MENU_MPO_FRIENDLY_FIRE,
	T_MENU_MPO_FAST_SWITCH,
	T_MENU_MPO_FOOTSTEPS,
	T_MENU_MPO_ALLOW_HOOK,
	T_MENU_MPO_SHOTSHELLS,

	T_MENU_MP_SERVER_IP_ADDRESS,
	T_MENU_MP_NO_LOCAL_GAMES,
	T_MENU_MP_STARTING_MAP,
	T_MENU_MP_SERVER_NAME,
	T_MENU_PLAYER_NAME,
	T_MENU_TEAM_NAME,

	T_MENU_QUIT_CONFIRM,

	T_MENU_YES,
	T_MENU_NO,
	T_MENU_SAVE,

	T_MENU_LOAD_CONFIG,				//cek[12-6-99]
	T_MENU_SAVE_CONFIG,				//cek[12-6-99]
	T_MENU_DELETE_CONFIG,			//cek[12-6-99]
	T_MENU_SELECT_CONFIG,			//cek[12-6-99]
	T_MENU_DELETE_SELECTION,		//cek[12-6-99]

	T_MENU_LOAD_GAME,				//cek[12-6-99]
	T_MENU_HEALTH,					//cek[12-6-99]
	T_MENU_ARMOR,					//cek[12-6-99]
	T_MENU_LEVEL,					//cek[12-6-99]
	T_MENU_MONSTERS,				//cek[12-6-99]
	T_MENU_SECRETS,					//cek[12-6-99]
	T_MENU_TIME,					//cek[12-6-99]
	T_MENU_TOTAL_TIME,				//cek[12-6-99]
	T_MENU_EPISODE,					//cek[12-6-99]

	T_MENU_3D_SOUND,

	T_MENU_SAVED,					//cek[12-7-99]
	T_MENU_LOADED,					//cek[12-7-99]
	T_MENU_DELETED,					//cek[12-7-99]

	T_MENU_MOUSE_SMOOTH,			//cek[12-7-99]
	T_MENU_WHEEL_UP,				//cek[12-7-99]
	T_MENU_WHEEL_DN,				//cek[12-7-99]

	T_MENU_NO_ALTTAB,				//cek[12-7-99]
	T_MENU_BLOODY,					//cek[12-7-99]
	T_MENU_WEAPON_BOB,				//cek[12-7-99]
	T_MENU_AUTOSWITCH,				//cek[12-7-99]

	T_MENU_MODULATE,				//cek[12-7-99]
	T_MENU_ENV_MAP,					//cek[12-7-99]
	T_MENU_BULLET_HOLES,			// SCG[1/4/00]: 

	T_MENU_JOY_FORWARD,				//cek[12-9-99]
	T_MENU_JOY_SIDE,				//cek[12-9-99]
	T_MENU_JOY_UP,					//cek[12-9-99]
	T_MENU_JOY_PITCH,				//cek[12-9-99]
	T_MENU_JOY_YAW,					//cek[12-9-99]
	T_MENU_JOY_USE,					//cek[12-9-99]
	T_MENU_JOY_CONFIGURE_AXIS,		//cek[12-9-99]
	T_MENU_JOY_HEADER,				//cek[12-9-99]
	T_MENU_JOY_HEADER2,				//cek[12-9-99]
	T_MENU_JOY_HEADER1,				//cek[12-9-99]
	T_MENU_JOY_THRESHOLD,			//cek[12-9-99]
	T_MENU_JOY_SENSITIVITY,			//cek[12-9-99]

	T_MENU_CTF,						//cek[12-10-99]
	T_MENU_MULTIPLAYER_BACK,		//cek[12-10-99]
	TEMP_T_MENU_CONNECTSPEED_3,		//cek[12-10-99]
	T_MENU_AUTO,					//cek[12-10-99]
	T_MENU_TEAM_1,					//cek[12-10-99]
	T_MENU_TEAM_2,					//cek[12-10-99]

	T_MENU_PLAY_INTRO,				//cek[12-13-99]
	T_MENU_SKILL_SYSTEM,			//cek[12-13-99]
	T_MENU_MOUSE_SPEED,				//cek[12-13-99]

	T_MENU_SIDEKICK_GET,			// cek[1-3-00]
	T_MENU_SIDEKICK_COME,			// cek[1-3-00]
	T_MENU_SIDEKICK_ATTACK,			// cek[1-3-00]
	T_MENU_SIDEKICK_BACK0FF,		// cek[1-3-00]
	T_MENU_SIDEKICK_STAY,			// cek[1-3-00]

	T_MENU_KCC_WEAPON_SELECT,		// cek[1-4-00]

	T_MENU_HUD_CYCLE,				// cek[1-5-00]
	T_MENU_HUD_NEXT,				// cek[1-5-00]
	T_MENU_HUD_PREV,				// cek[1-5-00]
	T_MENU_HUD_USE,					// cek[1-5-00]

	T_MENU_KCC_TALK,				// cek[1-11-00]
	T_MENU_KCC_SCOREBOARD,			// SCG[1/13/00]: 
	T_MENU_KCC_SAY_TEAM,			// cek[1-22-00]
	T_MENU_KEY_ASSIGNED,			// cek[1-22-00]
	T_MENU_KEY_CONTINUE,				// cek[1-22-00]

	T_MENU_MPLAYER_GAME,
	T_MENU_MPLAYER_COMM,
	T_MENU_CONTINUE,
	T_MENU_DLG_MPLAYER,
	T_MENU_DLG_COMM,

	T_MENU_WEAPON,					//cek[3-6-00]: for weapon disable feature.

	T_MENU_CANCEL,

	T_MENU_PLANET_DK,
	T_MENU_PLANET_DK_MSG
};


enum tongue_menu_options_enum
{
	T_MENU_ALWAYS_RUN = 0,
	T_MENU_LOOKSPRING,
	T_MENU_LOOKSTRAFE,
	T_MENU_AUTO_TARGETING,
	T_MENU_CROSSHAIR,
	T_MENU_WEAPON_VISIBLE,
	T_MENU_SUBTITLES,


	T_MENU_VOLUME_SOUNDFX,
	T_MENU_VOLUME_MUSIC,
	T_MENU_VOLUME_CINE,

	T_MENU_VIDEO_MODE_1,
	T_MENU_VIDEO_MODE_2,
	T_MENU_VIDEO_APPLY_CHANGES,

	T_MENU_VIDEO_FULLSCREEN,
// SCG[12/5/99]: 	T_MENU_VIDEO_STIPPLE_ALPHA,
	T_MENU_VIDEO_SHADOWS,
	T_MENU_VIDEO_DRIVER,
	T_MENU_VIDEO_RESOLUTION,
	T_MENU_VIDEO_SCREEN_SIZE,
	T_MENU_VIDEO_BRIGHTNESS,
	T_MENU_VIDEO_TEXTURE_QUALITY,
	T_MENU_OPTS_TRANSLUCENCY,
	T_MENU_OPTS_TESSELLATION,

	T_MENU_NEWGAME_SKILL_EASY,
	T_MENU_NEWGAME_SKILL_MEDIUM,
	T_MENU_NEWGAME_SKILL_HARD,

	T_MENU_VIDEO_SNOW_RAIN,			// cek[1-11-00]
	T_MENU_VIDEO_SHOW_FOG
};

enum tongue_weapon_names
{
	T_WEAPON_NO_AMMO = 0,
	T_WEAPON_BALLISTA,
	T_WEAPON_BALLISTA_AMMO,
	T_WEAPON_BOLTER,
	T_WEAPON_BOLTER_AMMO,
	T_WEAPON_C4,
	T_WEAPON_C4_AMMO,
//	T_WEAPON_CELESTRIL,						// SCG[11/28/99]: 
//	T_WEAPON_CELESTRIL_AMMO,				// SCG[11/28/99]: 
	T_WEAPON_DAIKATANA,
//	T_WEAPON_DAIKATANA_BANISH,				// SCG[11/28/99]: 
//	T_WEAPON_DAIKATANA_BARRIER,				// SCG[11/28/99]: 
//	T_WEAPON_DAIKATANA_DANCING,				// SCG[11/28/99]:		
//	T_WEAPON_DAIKATANA_MELEE,				// SCG[11/28/99]: 
//	T_WEAPON_DAIKATANA_POSSESSION,			// SCG[11/28/99]: 
//	T_WEAPON_DAIKATANA_PROTEUS,				// SCG[11/28/99]: 
	T_WEAPON_DISCUS,
	T_WEAPON_DISCUS_AMMO,
	T_WEAPON_DISRUPTOR,
//	T_WEAPON_FLASHLIGHT,					// SCG[11/29/99]: 
	T_WEAPON_GLOCK,
	T_WEAPON_GLOCK_AMMO,
	T_WEAPON_HAMMER,
	T_WEAPON_IONBLASTER,
	T_WEAPON_IONBLASTER_AMMO,
	T_WEAPON_KINETICORE,
	T_WEAPON_KINETICORE_AMMO,
	T_WEAPON_METAMASER,
	T_WEAPON_METAMASER_AMMO,
//	T_WEAPON_MIDAS,							// SCG[11/28/99]: 
//	T_WEAPON_MIDAS_AMMO,					// SCG[11/28/99]: 
	T_WEAPON_NIGHTMARE,
	T_WEAPON_NIGHTMARE_AMMO,
	T_WEAPON_NOVABEAM,
	T_WEAPON_NOVABEAM_AMMO,
	T_WEAPON_RIPGUN,
	T_WEAPON_RIPGUN_AMMO,
	T_WEAPON_SHOCKWAVE,
	T_WEAPON_SHOCKWAVE_AMMO,
	T_WEAPON_SHOTCYCLER,
	T_WEAPON_SHOTCYCLER_AMMO,
	T_WEAPON_SIDEWINDER,
	T_WEAPON_SIDEWINDER_AMMO,
	T_WEAPON_SILVERCLAW,
	T_WEAPON_SLUGGER,
	T_WEAPON_SLUGGER_AMMO,
	T_WEAPON_STAVROS,
	T_WEAPON_STAVROS_AMMO,
	T_WEAPON_SUNFLARE,
	T_WEAPON_SUNFLARE_AMMO,
//	T_WEAPON_TAZERHOOK,						// SCG[11/28/99]: 
	T_WEAPON_TRIDENT,
	T_WEAPON_TRIDENT_AMMO,
	T_WEAPON_VENOMOUS,
	T_WEAPON_VENOMOUS_AMMO,
	T_WEAPON_WYNDRAX,
	T_WEAPON_WYNDRAX_AMMO,
	T_WEAPON_ZEUS,
	T_WEAPON_ZEUS_AMMO,
	T_WEAPON_GASHANDS
};

enum tongue_armor_enums
{
	T_ARMOR_PLASTEEL = 0,
	T_ARMOR_CHROMATIC,
	T_ARMOR_SILVER,
	T_ARMOR_GOLD,
	T_ARMOR_CHAINMAIL,
	T_ARMOR_BLACKADAMANT,
	T_ARMOR_KEVLAR,
	T_ARMOR_EBONITE
};


enum tongue_monster_enums
{
	T_MONSTER_BATTLEBOAR = 0,
	T_MONSTER_PRISONER_BLACK,
	T_MONSTER_BUBOID,
	T_MONSTER_CAMBOT,
	T_MONSTER_CENTURION,
	T_MONSTER_CERBERUS,
	T_MONSTER_CHAINGANG,
	T_MONSTER_COLUMN,
	T_MONSTER_CROX,
// SCG[12/5/99]: 	T_MONSTER_CYCLOPS,
	T_MONSTER_DEATHSPHERE,
	T_MONSTER_DOOMBAT,
	T_MONSTER_DRAGON,
	T_MONSTER_DWARF,
	T_MONSTER_FEMGANG,
	T_MONSTER_FERRYMAN,
	T_MONSTER_FLETCHER,
	T_MONSTER_FROGINATOR,
	T_MONSTER_GARROTH,
	T_MONSTER_GOLDFISH,
	T_MONSTER_GRIFFON,
	T_MONSTER_HARPY,
	T_MONSTER_INMATER,
	T_MONSTER_KAGE,
// SCG[2/13/00]: T_MONSTER_KINGMINOS,
	T_MONSTER_KNIGHT1,
	T_MONSTER_KNIGHT2,
	T_MONSTER_LABMONKEY,
	T_MONSTER_CRYOTECH,
	T_MONSTER_LASERGAT,
	T_MONSTER_LYCANTHIR,
	T_MONSTER_MEDUSA,
// SCG[2/13/00]: 	T_MONSTER_MINOTAUR,
	T_MONSTER_MISHIMAGUARD,
	T_MONSTER_NHARRE,
	T_MONSTER_PLAGUERAT,
	T_MONSTER_PIPERAT,
	T_MONSTER_PRIEST,
	T_MONSTER_PRISONER,
	T_MONSTER_PROTOPOD,
	T_MONSTER_PSYCLAW,
	T_MONSTER_RAGEMASTER,
	T_MONSTER_ROCKETGANG,
	T_MONSTER_ROCKETMP,
	T_MONSTER_ROTWORM,
	T_MONSTER_SATYR,
	T_MONSTER_SEALCOMMANDO,
// SCG[12/5/99]: 	T_MONSTER_SEALDIVER,
	T_MONSTER_SEALCAPTAIN,
	T_MONSTER_SEALGIRL,
	T_MONSTER_SHARK,
	T_MONSTER_SLAUGHTERSKEET,
	T_MONSTER_SKELETON,
	T_MONSTER_SKINNYWORKER,
	T_MONSTER_FATWORKER,
	T_MONSTER_SLUDGEMINION,
	T_MONSTER_SMALLSPIDER,
	T_MONSTER_SPIDER,
	T_MONSTER_STAVROS,
	T_MONSTER_SURGEON,
	T_MONSTER_THIEF,
	T_MONSTER_THUNDERSKEET,
// SCG[12/5/99]: 	T_MONSTER_TRACKATTACK,
	T_MONSTER_UZIGANG,
	T_MONSTER_PRISONER_WHITE,
	T_MONSTER_WIZARD,
	T_MONSTER_WYNDRAX,
	T_MONSTER_SEAGULL,
	T_MONSTER_FIREFLY,
	T_MONSTER_WISP,
	T_MONSTER_MIKIKOMON,
	T_MONSTER_GHOST,
	T_MONSTER_DOPEFISH
};

enum tongue_world
{
	T_TRIGGERS_COUNTER = 0,
	T_TRIGGERS_SEQUENCE_COMPLETE,

	T_MUST_HAVE_KEY,
	T_NOT_PROPER_KEY,
	T_CANT_OPEN_HERE,

	T_POWERUPS_POISON_EXPIRE,
	T_POWERUPS_OXYLUNG_EXPIRE,
	T_POWERUPS_ENVIROSUIT_EXPIRE,
	T_POWERUPS_MEGASHIELD_EXPIRE,
	T_POWERUPS_WRAITHORB_EXPIRE,
	T_POWERUPS_BOOST_POWER_EXPIRE,
	T_POWERUPS_BOOST_ATTACK_EXPIRE,
	T_POWERUPS_BOOST_SPEED_EXPIRE,
	T_POWERUPS_BOOST_ACRO_EXPIRE,
	T_POWERUPS_BOOST_VITA_EXPIRE,

	T_PLAYER_JOINING_GAME,
	T_PLAYER_EXITED_LEVEL,

	T_HIRO_MIYAMOTO, 
	T_SUPERFLY_JOHNSON,
	T_MIKIKO_IBIHARA,

	T_PLAYER_SELF_SPAM_KICK,
	T_PLAYER_SPAM_KICK,
	T_PLAYER_TIME_LIMIT_HIT,
	T_PLAYER_FRAG_LIMIT_HIT,
	T_TELL_CMD_UNKNOWN_PLAYER,

	T_NO_EXIT_WITHOUT_SIDEKICKS,
	T_NO_EXIT_WITHOUT_KEY,
	T_PLAYER_POISON,

	T_FOUND_SECRET,							// cek[1-3-00]
	T_POWERUPS_MANASKULL_EXPIRE				// cek[2-9-00]
};


enum tongue_deathsmg_self_enums
{
	T_DEATHMSGSELF_FELL = 0,
	T_DEATHMSGSELF_DROWNED,
	T_DEATHMSGSELF_LAVA,
	T_DEATHMSGSELF_SLIME,
	T_DEATHMSGSELF_POISON,
	T_DEATHMSGSELF_KILLBRUSH,
	T_DEATHMSGSELF_TELEFRAG,
	T_DEATHMSGSELF_CRUSHED,

	T_DEATHMSGSELF_C4
};

enum tongue_deathmsg_daikatana_enum
{
	T_DEATHMSGWEAPON_DK_1
};

enum tongue_deathmsg_weapons_enum1
{
	T_DEATHMSGWEAPON_DISRUPTOR,
	T_DEATHMSGWEAPON_GASHANDS,
	T_DEATHMSGWEAPON_IONBLASTER,
	T_DEATHMSGWEAPON_C4,
	T_DEATHMSGWEAPON_SHOTCYCLER,
	T_DEATHMSGWEAPON_SIDEWINDER,
	T_DEATHMSGWEAPON_SHOCKWAVE
};

enum tongue_deathmsg_weapons_enum2
{
	T_DEATHMSGWEAPON_DISCUSS,
	T_DEATHMSGWEAPON_VENOMOUS,
	T_DEATHMSGWEAPON_SUNFLARE,
	T_DEATHMSGWEAPON_HAMMER,
	T_DEATHMSGWEAPON_TRIDENT,
	T_DEATHMSGWEAPON_ZEUS
};

enum tongue_deathmsg_weapons_enum3
{
	T_DEATHMSGWEAPON_SILVERCLAW,
	T_DEATHMSGWEAPON_BOLTER,
	T_DEATHMSGWEAPON_BALLISTA,
	T_DEATHMSGWEAPON_STAVROS,
	T_DEATHMSGWEAPON_WYNDRAX,
	T_DEATHMSGWEAPON_NHARRE
};

enum tongue_deathmsg_weapons_enum4
{
	T_DEATHMSGWEAPON_GLOCK,
	T_DEATHMSGWEAPON_SLUGGER,
	T_DEATHMSGWEAPON_RIPGUN,
	T_DEATHMSGWEAPON_CORDITE,
	T_DEATHMSGWEAPON_KINETICORE,
	T_DEATHMSGWEAPON_NOVABEAM,
	T_DEATHMSGWEAPON_METAMASER
};


enum tongue_scoreboard_enums
{
	T_SCOREBOARD_NAME = 0,
	T_SCOREBOARD_KILLS,
	T_SCOREBOARD_PING,
	T_SCOREBOARD_TIME,
	T_SCOREBOARD_SHOTS,
	T_SCOREBOARD_HITS,
	T_SCOREBOARD_DIED,
	T_SCOREBOARD_SCORE
};


enum tongue_difficulty_enums
{
	T_MENU_DIFFICULTY_HEADER = 0,
	T_MENU_DIFFICULTY_EASY,
	T_MENU_DIFFICULTY_MEDIUM,
	T_MENU_DIFFICULTY_HARD
};


enum tongue_skincolors_enums
{
	T_MENU_SKINCOLOR_1 = 0,
	T_MENU_SKINCOLOR_2,
	T_MENU_SKINCOLOR_3,
	T_MENU_SKINCOLOR_4
};


enum tongue_statbar_enums
{	
	T_SKILLS_POWER = 0,
	T_SKILLS_ATTACK,
	T_SKILLS_SPEED,
	T_SKILLS_ACRO,
	T_SKILLS_VITALITY,

	T_STATBAR_ARMOR,
	T_STATBAR_HEALTH,
	T_STATBAR_AMMO,
	T_STATBAR_XPLEVEL,
	T_STATBAR_FRAGS,

	T_XPLEVEL_LEVELUP,
	T_XPLEVEL_SELECT,
	T_XPLEVEL_ASSIGN,

	T_TRANSITION_LOADING
};


enum tongue_weapon_misc_enums
{
  T_WEAPON_MISC_C4DESTABILIZING = 0
};



enum tongue_sidekick_enums
{
	T_SIDEKICK_CMD_GET = 0,
	T_SIDEKICK_CMD_COME,
	T_SIDEKICK_CMD_STAY,
	T_SIDEKICK_CMD_ATTACK,
	T_SIDEKICK_CMD_BACKOFF,

	T_SIDEKICK_QUESTION_GET
};

enum tongue_ctf_enums
{
	T_FLAG_TEAM1,
	T_FLAG_TEAM2,
	T_TEAM_NAMES,
	
	T_CTF_FLAG_NAME,

	T_CTF_RED_TEAM_NAME,
	T_CTF_BLUE_TEAM_NAME,
	T_CTF_CHROME_TEAM_NAME,
	T_CTF_METAL_TEAM_NAME,
	T_CTF_GREEN_TEAM_NAME,
	T_CTF_ORANGE_TEAM_NAME,
	T_CTF_PURPLE_TEAM_NAME,
	T_CTF_YELLOW_TEAM_NAME,

	T_CTF_SCORE,
	T_CTF_YOU_CAPTURED,
	T_CTF_YOUR_TEAM_CAPTURED,
	T_CTF_OTHER_TEAM_CAPTURED,

	T_CTF_YOU_HAVE_GOT_FLAG,
	T_CTF_GRABBED_FLAG,
	T_CTF_STOLEN_FLAG,
	T_CTF_FLAG_RETURNED,

	T_CTF_INVALID_TEAM,
	T_CTF_ON_TEAM,
	T_CTF_ALREADY_ON_TEAM,
	T_CTF_PLAYER_JOINED,

	T_CTF_TEAM_WON,
	T_CTF_TIE,
	T_CTF_TIME_EXPIRED,
	T_CTF_LIMIT_REACHED
};

enum tongue_deathtag_enums
{
	TONGUE_DT_PACK,
	TONGUE_DT_TEAM_PACK,
	TONGUE_DT_SCORE_LIMIT,
	TONGUE_DT_TIME_ROUT,
	TONGUE_DT_TIME_OUT,

	TONGUE_DT_O_TEAM_GRABBED,

	TONGUE_DT_Y_POINT,
	TONGUE_DT_Y_POINTS,
	TONGUE_DT_O_POINT,
	TONGUE_DT_O_POINTS,

	TONGUE_DT_YOU_SCORED,
	TONGUE_DT_Y_TEAM_SCORED,
	TONGUE_DT_O_TEAM_SCORED
};

// separate include .h files based on language
#ifdef TONGUE_ENGLISH
  #include "l_english.h"
#else
  #ifdef TONGUE_FRENCH
    #include "l_french.h"
  #else
    #ifdef TONGUE_GERMAN
      #include "l_german.h"
    #else
      #ifdef TONGUE_ITALIAN
        #include "l_italian.h"
      #else
        #ifdef TONGUE_SPANISH
          #include "l_spanish.h"
        #else
           #ifdef TONGUE_JAPANESE
             #include "l_japanese.h"
           #endif
        #endif
      #endif
    #endif
  #endif
#endif
